server:
  port: 8888
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: file:C:/spring-cloud/config-repo
          clone-on-start: true
          default-label: main
  security:
    user:
      name: root
      password: s3cr3t

eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/